## cv2 vs numpy

**0과 255의 범위를 초과**하는 값을 다루는 방식이 모듈 numpy와 cv2 사이에 **차이점**이 있다.  
  
ex) **-1 (0 미만 값)**의 경우,  
* numpy : **255**로 처리
* cv2 : **0**으로 처리  
  
ex) **256 (255 초과 값)**의 경우, (**overflow**)     
* numpy : **0**로 처리
* cv2 : **255**으로 처리  
  
  
> 따라서, np.array()에 50을 더해서 255를 초과하면 numpy에서 0으로 처리하므로, np.min()을 찍어보면 0이 생긴다. 

In [12]:
import cv2
import numpy as np

x = np.uint8([250]) # cv2.imread 시 uint8 범위 (0~255)
y = np.uint8([10]) 

print(cv2.add(x,y)) # 250 + 10 = 260 => 255
print(x+y)          # 250 + 10 = 260 => 260 % 256 = 4

[[255]]
[4]


## cf. np.where과 cv2.add ==> 1ms 차이

In [15]:
# sol1) np.where 이용

import numpy as np
import cv2

tm = cv2.TickMeter()
tm.start()

img = cv2.imread('lenna.bmp', cv2.IMREAD_GRAYSCALE)
print(np.min(img), np.max(img))

img2 = img.copy()

img3 = img2[200:400, 200:400] # 별개의 주소

img2[200:400, 200:400] = np.where(img3 > 205, 255, img3 + 50)
print(np.min(img2), np.max(img2))
print(np.min(img2[200:400, 200:400]), np.max(img2[200:400, 200:400]))

cv2.imwrite('lenna_50_1.bmp', img2)
print(img2[200:400, 200:400])

tm.stop()
print('np.where time :', tm.getTimeMilli())

22 239
22 255
73 255
[[120 114 125 ...  94  94  93]
 [113 115 126 ...  96  95  96]
 [124 128 131 ...  94  99 108]
 ...
 [ 86  93  89 ... 158 166 155]
 [ 95  91  88 ... 166 162 160]
 [ 97  98  90 ... 161 162 168]]
np.where time : 10.228900000000001


In [16]:
# sol2) cv2.add() 이용

import numpy as np
import cv2

tm = cv2.TickMeter()
tm.start()

img = cv2.imread('lenna.bmp', cv2.IMREAD_GRAYSCALE)
print(np.min(img), np.max(img))

img2 = img.copy()

img2[200:400, 200:400] = cv2.add(img2[200:400, 200:400], 50)
print(np.min(img2), np.max(img2))
print(np.min(img2[200:400, 200:400]), np.max(img2[200:400, 200:400]))

cv2.imwrite('lenna_50_2.bmp', img2)
print(img2[200:400, 200:400])

tm.stop()
print('np.where time :', tm.getTimeMilli())

22 239
22 255
73 255
[[120 114 125 ...  94  94  93]
 [113 115 126 ...  96  95  96]
 [124 128 131 ...  94  99 108]
 ...
 [ 86  93  89 ... 158 166 155]
 [ 95  91  88 ... 166 162 160]
 [ 97  98  90 ... 161 162 168]]
np.where time : 9.389700000000001


In [3]:
# sol2) cv2.add() 이용 ==> 제출용

import cv2

img = cv2.imread('lenna.bmp', cv2.IMREAD_GRAYSCALE)
img2 = img.copy()
img2[200:400, 200:400] = cv2.add(img2[200:400, 200:400], 50)
cv2.imwrite('lenna_50.bmp', img2)

True

## 깊은 복사 vs 얕은 복사

In [20]:
arr = np.array([[1, 2, 3], [4,5,6]])
print(arr)

print()

arr2 = arr[:, 1:].copy()
print(arr2)

print()

arr2 += 10
print(arr2)

print()

arr += 10
print(arr)
print(arr2)
# arr과 arr2는 별개! (copy() 했으므로)

[[1 2 3]
 [4 5 6]]

[[2 3]
 [5 6]]

[[12 13]
 [15 16]]

[[11 12 13]
 [14 15 16]]
[[12 13]
 [15 16]]


In [7]:
arr = np.array([1,2,3])
arr1 = arr[:2] # 이건 다른 주소
arr2 = arr # 이건 같은 주소

print(id(arr), id(arr1), id(arr2))

2017283151312 2017283151232 2017283151312
