* 비율은 200, 300으로
* sol1) 그레이스케일 -> 이진화 -> (필요시) 침식, 팽창 -> 허프 변환 직선 검출 -> 네 모서리 좌표 -> getPerspectiveTransform, warpPerspective
* sol2) 허프 변환 직선 검출 -> 네 모서리 좌표 -> getPerspectiveTransform, warpPerspective

In [1]:
# sol2로 했을 때

import cv2
import numpy as np
import math

def hough_lines():
    src = cv2.imread('test_resize.png', cv2.IMREAD_GRAYSCALE)
    
    edge = cv2.Canny(src, 50, 150)
    lines = cv2.HoughLines(edge, 1, math.pi / 180, 250)
    
    dst = cv2.cvtColor(edge, cv2.COLOR_GRAY2BGR)
    
    if lines is not None:
        for i in range(lines.shape[0]):
            rho = lines[i][0][0]
            theta = lines[i][0][1]
            cos_t = math.cos(theta)
            sin_t = math.sin(theta)
            x0, y0 = rho * cos_t, rho * sin_t
            alpha = 1000
            pt1 = (int(x0 - alpha * sin_t), int(y0 + alpha * cos_t))
            pt2 = (int(x0 + alpha * sin_t), int(y0 - alpha * cos_t))
            cv2.line(dst, pt1, pt2, (0, 0, 255), cv2.LINE_AA)
            
    cv2.imshow('src', src)
    cv2.imshow('dst', dst)
    cv2.waitKey()
    cv2.destroyAllWindows()
        
hough_lines()

![](result1.png)

In [2]:
# 적응형 이진화 => 여기서 팽창, 침식 적용해도 될듯!

import cv2
import numpy as np
import math

def on_trackbar(pos):
    bsize = pos
    if bsize % 2 == 0: bsize = bsize - 1
    if bsize < 3 : bsize = 3
        
    dst = cv2.adaptiveThreshold(src, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                               cv2.THRESH_BINARY, bsize, 5)
    
    cv2.imshow('dst', dst)
    
    
src = cv2.imread('test_resize.png', cv2.IMREAD_GRAYSCALE)

cv2.imshow('src', src)

cv2.namedWindow('dst')
cv2.createTrackbar('Block Size', 'dst', 0, 750, on_trackbar) # bisze = 749!
cv2.setTrackbarPos('Block Size', 'dst', 11)

cv2.waitKey()
cv2.destroyAllWindows()

![](result2.png)

In [3]:
# Otsu 방식

import cv2

src = cv2.imread('test_resize.png', cv2.IMREAD_GRAYSCALE)

cv2.imshow('src', src)

ret, otsu = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

cv2.imshow('otsu', otsu)

cv2.waitKey()
cv2.destroyAllWindows()

![](result3.png)

In [4]:
# Otsu 후 침식, 팽창

import cv2

# 1. Otsu
src = cv2.imread('test_resize.png', cv2.IMREAD_GRAYSCALE)
cv2.imshow('src', src)

ret, otsu = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
cv2.imshow('otsu', otsu)

# 2. Morphology
mask = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
erode = cv2.erode(otsu, mask, iterations = 1)
dilate = cv2.dilate(erode, mask, iterations = 1)
cv2.imshow('erode', erode)
cv2.imshow('dilate', dilate)

cv2.waitKey()
cv2.destroyAllWindows()

![](result4.png)

In [34]:
# Otsu -> 침식, 팽창 -> 허프 직선 검출1

import cv2
import numpy as np
import math

# 1. Otsu
src = cv2.imread('test_resize.png', cv2.IMREAD_GRAYSCALE)
cv2.imshow('src', src)

ret, otsu = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
cv2.imshow('otsu', otsu)

# 2. Morphology
mask = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
erode = cv2.erode(otsu, mask, iterations = 1)
dilate = cv2.dilate(erode, mask, iterations = 2) # 한번 더 팽창해서 중간 구멍 제거
cv2.imshow('erode', erode)
cv2.imshow('dilate', dilate)

# 3. hough line detection (hough_lines(), p.73)
edge = cv2.Canny(dilate, 50, 150)
lines = cv2.HoughLines(edge, 1, math.pi / 180, 114) # threshold를 250 -> 114로!!

print(lines) # 직선정보(rho, theta)를 저장할 출력 벡터! (네점의 좌표 X)

dst = cv2.cvtColor(edge, cv2.COLOR_GRAY2BGR)

if lines is not None:
    print('yes!') # Q. 왜 여기도 안들어감....? => 위에 threshold 수정하기!
    for i in range(lines.shape[0]):
        rho = lines[i][0][0]
        theta = lines[i][0][1]
        cos_t = math.cos(theta)
        sin_t = math.sin(theta)
        x0, y0 = rho * cos_t, rho * sin_t
        alpha = 1000
        pt1 = (int(x0 - alpha * sin_t), int(y0 + alpha * cos_t))
        pt2 = (int(x0 + alpha * sin_t), int(y0 - alpha * cos_t))
        cv2.line(dst, pt1, pt2, (0, 0, 255), cv2.LINE_AA) # 빨간색!
        
cv2.imshow('dst', dst)

cv2.waitKey()
cv2.destroyAllWindows()

[[[-162.           2.5481806]]

 [[ -31.           2.9321532]]

 [[ 352.           1.2566371]]

 [[  82.           1.3613569]]]
yes!


1. threshold = 250 일때 (**lines == None**)
![](result5.png)
2. threshold = 100 일때 (**lines != None**)
![](result6.png)

In [39]:
# Otsu -> 침식, 팽창 -> 허프 직선 검출2

import cv2
import numpy as np
import math

# 1. Otsu
src = cv2.imread('test_resize.png', cv2.IMREAD_GRAYSCALE)
cv2.imshow('src', src)

ret, otsu = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
cv2.imshow('otsu', otsu)

# 2. Morphology
mask = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
erode = cv2.erode(otsu, mask, iterations = 1)
dilate = cv2.dilate(erode, mask, iterations = 2) # 한번 더 팽창해서 중간 구멍 제거
cv2.imshow('erode', erode)
cv2.imshow('dilate', dilate)

# 3. hough line detection (hough_line_segments(), p.79)
edge = cv2.Canny(dilate, 50, 150)
# ***여기가 다름***
lines = cv2.HoughLinesP(edge, 1, math.pi / 180, 114, minLineLength=50, maxLineGap=100)
    
dst = cv2.cvtColor(edge, cv2.COLOR_GRAY2BGR)
print(lines)
if lines is not None:
    print('yes!')
    for i in range(lines.shape[0]):
        pt1 = (lines[i][0][0], lines[i][0][1])
        pt2 = (lines[i][0][2], lines[i][0][3])
        cv2.line(dst, pt1, pt2, (0, 0, 255), 2, cv2.LINE_AA) # 2!!
        
cv2.imshow('dst', dst)
        
cv2.waitKey()
cv2.destroyAllWindows()

[[[221  39 362 248]]

 [[ 49  78 103 334]]

 [[110 334 356 254]]

 [[ 50  73 193  43]]]
yes!


![](result7.png)

In [41]:
# Otsu -> 침식, 팽창 -> 직접 직선의방정식으로부터 네 꼭지점 좌표 구하기..!ㅠㅠ
# 이 방법 X! (음수 좌표 나옴...)

import cv2
import numpy as np
import math

# 1. Otsu
src = cv2.imread('test_resize.png', cv2.IMREAD_GRAYSCALE)
cv2.imshow('src', src)

ret, otsu = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
cv2.imshow('otsu', otsu)

# 2. Morphology
mask = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
erode = cv2.erode(otsu, mask, iterations = 1)
dilate = cv2.dilate(erode, mask, iterations = 2) # 한번 더 팽창해서 중간 구멍 제거
cv2.imshow('erode', erode)
cv2.imshow('dilate', dilate)

# 3
edge = cv2.Canny(dilate, 50, 150)
lines = cv2.HoughLines(edge, 1, math.pi / 180, 114) # threshold를 250 -> 114로!!

print(lines) # 직선정보(rho, theta)를 저장할 출력 벡터! (네점의 좌표 X)

points = []

if lines is not None:
    for i in range(lines.shape[0]):
        c1 = lines[(i+4)%4][0][0] # rho1 
        c2 = lines[(i+5)%4][0][0] # rho2
        theta1 = lines[(i+4)%4][0][1]
        theta2 = lines[(i+5)%4][0][1]
        a1 = math.cos(theta1)
        a2 = math.cos(theta2)
        b1 = math.sin(theta1)
        b2 = math.sin(theta2)
        
        x = int((b2*c1 - b1*c2) / (a1*b2 - a2*b1))
        y = int((c1 - a1*x) / b1)
        
        points.append([x, y])

print(points)
        
cv2.waitKey()
cv2.destroyAllWindows()

[[[-162.           2.5481806]]

 [[ -31.           2.9321532]]

 [[ 352.           1.2566371]]

 [[  82.           1.3613569]]]
[[-43, -353], [103, 335], [2547, -457], [220, 37]]


### 성공! (각 꼭지점 좌표 구해서 투시 변환)

In [5]:
# Otsu -> 침식, 팽창 -> HoughLinesP & 직접 좌표값들 보고 꼭지점 좌표 선택하기 ==> < 성공 >
# 이 다음에 두 수평선 그룹으로 나눠서 교점 좌표 구하는 방식으로 해보기!

import cv2
import numpy as np
import math

# 1. Otsu
src = cv2.imread('test_resize.png', cv2.IMREAD_GRAYSCALE)
cv2.imshow('src', src)

ret, otsu = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
cv2.imshow('otsu', otsu)

# 2. Morphology
mask = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
erode = cv2.erode(otsu, mask, iterations = 1)
dilate = cv2.dilate(erode, mask, iterations = 2) # 한번 더 팽창해서 중간 구멍 제거
cv2.imshow('erode', erode)
cv2.imshow('dilate', dilate)

# 3. hough line detection (hough_line_segments(), p.79)
edge = cv2.Canny(dilate, 50, 150)
# ***여기가 다름***
lines = cv2.HoughLinesP(edge, 1, math.pi / 180, 114, minLineLength=50, maxLineGap=100)
    
dst = cv2.cvtColor(edge, cv2.COLOR_GRAY2BGR)
print(lines)
if lines is not None:
    print('yes!')
    for i in range(lines.shape[0]):
        pt1 = (lines[i][0][0], lines[i][0][1])
        pt2 = (lines[i][0][2], lines[i][0][3])
        cv2.line(dst, pt1, pt2, (0, 0, 255), 2, cv2.LINE_AA) # 2!!
        
cv2.imshow('dst', dst)

# 4. 네 모서리 좌표들 직접 넣기 ==> ***src_pts = np.zeros([4, 2], dtype = np.float32)
points = np.zeros([4, 2], dtype = np.float32)

points[0, :] = np.array([lines[1][0][0], lines[1][0][1]]).astype(np.float32) # 좌상단
points[1, :] = np.array([lines[0][0][0], lines[0][0][1]]).astype(np.float32) # 우상단
points[2, :] = np.array([lines[0][0][2], lines[0][0][3]]).astype(np.float32) # 우하단
points[3, :] = np.array([lines[1][0][2], lines[1][0][3]]).astype(np.float32) # 좌하단

print(points)

cv2.circle(src, (lines[1][0][0], lines[1][0][1]), 5, (0, 0, 255), -1)
cv2.circle(src, (lines[0][0][0], lines[0][0][1]), 5, (0, 0, 255), -1)
cv2.circle(src, (lines[0][0][2], lines[0][0][3]), 5, (0, 0, 255), -1)
cv2.circle(src, (lines[1][0][2], lines[1][0][3]), 5, (0, 0, 255), -1)
cv2.imshow('circle', src)

# 5. 투시 변환
w = 400 # dst 크기 사전에 지정
h = 600
            
# 좌상단부터 시계 방향으로 처리
dst_pts = np.array([[0, 0],
                    [w - 1, 0],
                    [w - 1, h - 1],
                    [0, h - 1]]).astype(np.float32)
            
pers_mat = cv2.getPerspectiveTransform(points, dst_pts) # M 구하기

src = cv2.imread('test_resize.png')

result = cv2.warpPerspective(src, pers_mat, (w, h)) # M 이용해 투시 변환
            
cv2.imshow('result', result)


cv2.waitKey()
cv2.destroyAllWindows()

[[[221  39 362 248]]

 [[ 49  78 103 334]]

 [[110 334 356 254]]

 [[ 50  73 193  43]]]
yes!
[[ 49.  78.]
 [221.  39.]
 [362. 248.]
 [103. 334.]]


![](result8.png)

### 성공! (평행선 그룹 간 intersections 자동으로 구해서 4방향 구분) ==> 함수로 쪼개기
참고 코드 : https://java2020.com/q/ktdcksju

In [1]:
import cv2
import numpy as np
import math

# 1. Otsu
src = cv2.imread('test_resize.png', cv2.IMREAD_GRAYSCALE)
cv2.imshow('src', src)

ret, otsu = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
cv2.imshow('otsu', otsu)

# 2. Morphology
mask = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
erode = cv2.erode(otsu, mask, iterations = 1)
dilate = cv2.dilate(erode, mask, iterations = 2) # 한번 더 팽창해서 중간 구멍 제거
cv2.imshow('erode', erode)
cv2.imshow('dilate', dilate)

# 3
edge = cv2.Canny(dilate, 50, 150)
lines = cv2.HoughLines(edge, 1, math.pi / 180, 114) # threshold를 250 -> 114로!!

print(lines) # 직선정보(rho, theta)를 저장할 출력 벡터! (네점의 좌표 X)

points = []

if lines is not None:
    for i in range(lines.shape[0]):
        c1 = lines[(i+4)%4][0][0] # rho1 
        c2 = lines[(i+5)%4][0][0] # rho2
        theta1 = lines[(i+4)%4][0][1]
        theta2 = lines[(i+5)%4][0][1]
        a1 = math.cos(theta1)
        a2 = math.cos(theta2)
        b1 = math.sin(theta1)
        b2 = math.sin(theta2)
        
        x = int((b2*c1 - b1*c2) / (a1*b2 - a2*b1))
        y = int((c1 - a1*x) / b1)
        
        points.append([x, y])

print(points)

cv2.waitKey()
cv2.destroyAllWindows()

[[[-162.           2.5481806]]

 [[ -31.           2.9321532]]

 [[ 352.           1.2566371]]

 [[  82.           1.3613569]]]
[[-43, -353], [103, 335], [2547, -457], [220, 37]]


In [2]:
from collections import defaultdict
def segment_by_angle_kmeans(lines, k=2, **kwargs):
    """Groups lines based on angle with k-means.

    Uses k-means on the coordinates of the angle on the unit circle 
    to segment `k` angles inside `lines`.
    """

    # Define criteria = (type, max_iter, epsilon)
    default_criteria_type = cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER
    criteria = kwargs.get('criteria', (default_criteria_type, 10, 1.0))
    flags = kwargs.get('flags', cv2.KMEANS_RANDOM_CENTERS)
    attempts = kwargs.get('attempts', 10)

    # returns angles in [0, pi] in radians
    angles = np.array([line[0][1] for line in lines])
    # multiply the angles by two and find coordinates of that angle
    pts = np.array([[np.cos(2*angle), np.sin(2*angle)]
                    for angle in angles], dtype=np.float32)

    # run kmeans on the coords
    labels, centers = cv2.kmeans(pts, k, None, criteria, attempts, flags)[1:]
    labels = labels.reshape(-1)  # transpose to row vec

    # segment lines based on their kmeans label
    segmented = defaultdict(list)
    for i, line in zip(range(len(lines)), lines):
        segmented[labels[i]].append(line)
    segmented = list(segmented.values())
    return segmented

In [3]:
segmented = segment_by_angle_kmeans(lines)
print(segmented)

[[array([[-162.       ,    2.5481806]], dtype=float32), array([[-31.       ,   2.9321532]], dtype=float32)], [array([[352.       ,   1.2566371]], dtype=float32), array([[82.       ,  1.3613569]], dtype=float32)]]


In [4]:
def intersection(line1, line2):
    """Finds the intersection of two lines given in Hesse normal form.

    Returns closest integer pixel locations.
    See https://stackoverflow.com/a/383527/5087436
    """
    rho1, theta1 = line1[0]
    rho2, theta2 = line2[0]
    A = np.array([
        [np.cos(theta1), np.sin(theta1)],
        [np.cos(theta2), np.sin(theta2)]
    ])
    b = np.array([[rho1], [rho2]])
    x0, y0 = np.linalg.solve(A, b)
    x0, y0 = int(np.round(x0)), int(np.round(y0))
    return [[x0, y0]]


def segmented_intersections(lines):
    """Finds the intersections between groups of lines."""

    intersections = []
    for i, group in enumerate(lines[:-1]):
        for next_group in lines[i+1:]:
            for line1 in group:
                for line2 in next_group:
                    intersections.append(intersection(line1, line2)) 

    return intersections

In [5]:
intersections = segmented_intersections(segmented)
print(intersections) # intersections[0][0] = [365, 252]

[[[365, 252]], [[220, 37]], [[103, 337]], [[47, 74]]]


In [6]:
# y값 기준 오름차순 정렬
intersections.sort(key = lambda x : x[0][1])
print(intersections)

# x값 기준 오름차순 정렬
intersections.sort(key = lambda x : x[0][0])
print(intersections)

[[[220, 37]], [[47, 74]], [[365, 252]], [[103, 337]]]
[[[47, 74]], [[103, 337]], [[220, 37]], [[365, 252]]]


In [7]:
# 시계 방향으로 좌표 정렬 (반으로 나눠서 크기 비교 두번씩)
intersections_sorted = np.zeros([4, 2], dtype = np.float32)
intersections.sort(key = lambda x : x[0][1]) # y값 기준 오름차순 정렬

if intersections[0][0][0] < intersections[1][0][0]:
    lu = intersections[0][0]
    ru = intersections[1][0]
else:
    lu = intersections[1][0]
    ru = intersections[0][0]
    
if intersections[2][0][0] < intersections[3][0][0]:
    rd = intersections[3][0]
    ld = intersections[2][0]
else:
    rd = intersections[2][0]
    ld = intersections[3][0]
    
    
intersections_sorted[0, :] = np.array(lu).astype(np.float32)
intersections_sorted[1, :] = np.array(ru).astype(np.float32)
intersections_sorted[2, :] = np.array(rd).astype(np.float32)
intersections_sorted[3, :] = np.array(ld).astype(np.float32)

print(intersections_sorted)

[[ 47.  74.]
 [220.  37.]
 [365. 252.]
 [103. 337.]]


In [9]:
# 점으로 각 꼭지점 표시
for i in range(4):
    cv2.circle(src, (intersections_sorted[i][0], intersections_sorted[i][1]), 5, (0, 0, 255), -1) # 클릭 시 빨간색 원
    
cv2.imshow('circle', src)
cv2.waitKey()
cv2.destroyAllWindows()

![](result9.png)

In [10]:
# 5. 투시 변환
w = 400 # dst 크기 사전에 지정
h = 600
            
# 좌상단부터 시계 방향으로 처리
dst_pts = np.array([[0, 0],
                    [w - 1, 0],
                    [w - 1, h - 1],
                    [0, h - 1]]).astype(np.float32)
            
pers_mat = cv2.getPerspectiveTransform(intersections_sorted, dst_pts) # M 구하기

src = cv2.imread('test_resize.png')

result = cv2.warpPerspective(src, pers_mat, (w, h)) # M 이용해 투시 변환
            
cv2.imshow('result', result)


cv2.waitKey()
cv2.destroyAllWindows()

![](result10.png)

<hr>