In [2]:
# NumPy를 import 한 후 __version__으로 확인 & as문을 사용해서 축약어 사용

import numpy as np

print(np.__version__)

1.16.2


In [3]:
# NumPy 배열의 생성 (1) ==> numpy array와 python list의 차이

arr = [1, 4, 2, 5, 3] # list
n_arr = np.array(arr) 
print(arr) # 콤마(,)와 함께 출력됨
print(type(arr))
print(n_arr) # 콤마(,)없이 출력됨
print(type(n_arr))

[1, 4, 2, 5, 3]
<class 'list'>
[1 4 2 5 3]
<class 'numpy.ndarray'>


In [4]:
# NumPy 배열의 특징 (1) ==> 배열의 모든 요소가 같은 타입이어야 함 / 타입 불일치 시 가능한 상위 타입 취함

arr = [3.14, 2, 5, 3]
n_arr = np.array(arr)
print(arr)
print(type(arr))
print(n_arr)
print(type(n_arr)) # int와 float이 섞여 있는 np.array는 모두 float 형으로 취하게 됨! (형변환)

[3.14, 2, 5, 3]
<class 'list'>
[3.14 2.   5.   3.  ]
<class 'numpy.ndarray'>


In [5]:
# 문자열과 실수와 정수가 섞여 있을 경우에는?

arr = ['3.14', 2., 5, 3]
n_arr = np.array(arr)
print(arr)
print(type(arr))
print(n_arr) # 모든 자료형을 포함할 수 있는 최상위 자료형인 "string"으로 모두 형변환!
print(type(n_arr)) 

['3.14', 2.0, 5, 3]
<class 'list'>
['3.14' '2.0' '5' '3']
<class 'numpy.ndarray'>


In [6]:
# NumPy 배열의 데이터 타입 ==> dtype을 사용한 명시적 자료형 설정

arr = [1, 4, 2, 5, 3]
n_arr = np.array(arr, dtype='float32')
print(arr)
print(type(arr))
print(n_arr) # 실수형 (32 bit float)
print(type(n_arr))

[1, 4, 2, 5, 3]
<class 'list'>
[1. 4. 2. 5. 3.]
<class 'numpy.ndarray'>


In [7]:
arr = ['3.14', 2., 5, 3]
n_arr = np.array(arr, dtype='float32') # 모두 float32 형으로 형변환! (float64면 3.14로 딱 출력됨)
print(arr)
print(type(arr))
print(n_arr) # 사용하는 pc에 따라서 [3.1400001  2.       5.      ] 이렇게 나올 수도!
print(type(n_arr))

['3.14', 2.0, 5, 3]
<class 'list'>
[3.14 2.   5.   3.  ]
<class 'numpy.ndarray'>


In [11]:
# NumPy 배열의 속성

nums = np.array([1, 4, 2, 5, 3])
print(nums)
print(nums.ndim) # 몇 차원인지 Rank 확인 가능
print(nums.shape) # 배열의 꼴 (모양) 확인 가능 ==> tuple (1차원에 5개 요소 존재)
print(len(nums.shape)) # 차원 확인 가능 (Rank)
print(nums.size) # 배열에 들어있는 총 전체 요소 개수 (차원 별로 x)

print()

# cf. nums.shape vs nums.size

nums2 = np.array([[1, 4, 2, 5, 3], [1, 2, 3, 4, 5]])
print(nums.shape)
print(nums2.shape) # shape : 차원별로 요소가 몇 개씩 있는지 tuple로 보여줌
print(nums.size)
print(nums2.size) # size : 배열에 존재하는 전체 요소 개수를 차원 상관없이 보여줌

print()

print(len(nums2)) # 2행이라서... 다차원의 경우에는 주의하기!!

[1 4 2 5 3]
1
(5,)
1
5

(5,)
(2, 5)
5
10

2


In [12]:
# NumPy 배열의 값 접근 ==> 표준 python 리스트의 구문을 그대로 따름

nums = np.array([1, 4, 2, 5, 3])
print(nums[::2]) # 배열명[start:stop:step] ==> step 값이 지정되지 않으면 기본 step=1

[1 2 3]


In [13]:
# NumPy 2차원 배열의 값 접근(1) ==> 2가지 방법!

nums = np.array([[1, 4, 2], [7, 5, 3]])
print(nums)
print(nums[0, 2]) # 1) 배열명[행, 열]
print(nums[0][2]) # 2) 배열명[행][열] ==> C or JAVA 스타일

[[1 4 2]
 [7 5 3]]
2
2


In [14]:
# NumPy 2차원 배열의 값 접근(2) ==> 배열명[슬라이스, 슬라이스] (차원별 슬라이싱)

print(nums)
print(nums[0:1, ]) # 행 차원만 [0:1] 슬라이싱 ==> 열 차원은 슬라이싱 x이므로 전부 다!
print(nums[0:1, :]) # 위와 동일
print(nums[:, 1:2]) # 행 차원은 전부, 열 차원은 [1:2]까지 슬라이싱
print(nums[1, 1:]) # 행 차원은 1행만, 열 차원은 [1:] 슬라이싱
print(nums[0:, 1:]) # 행 차원은 [0:] 슬라이싱, 열 차원은 [1:] 슬라이싱

[[1 4 2]
 [7 5 3]]
[[1 4 2]]
[[1 4 2]]
[[4]
 [5]]
[5 3]
[[4 2]
 [5 3]]


In [15]:
# NumPy 2차원 배열의 값 접근(3) ==> "범위로 슬라이싱" vs "특정 행/열 슬라이싱" 차이!!

print(nums[0:1, ]) # 범위로 슬라이싱
print(nums[0:1, :]) # 범위로 슬라이싱 ==> 위에 두개는 shape가 2차원 구조!
print(nums[0, :]) # 특정 행 슬라이싱 ==> 얘는 shape가 1차원 구조!

[[1 4 2]]
[[1 4 2]]
[1 4 2]
