## NumPy 2차원 배열의 값 접근 (슬라이싱)
* 파이썬 list & 넘파이 array
* 슬라이싱 & copy()

In [3]:
# 지난 시간 예제

import numpy as np
nums = np.array([[1, 4, 2], [7, 5, 3]])
print(nums[ 1: , 1:2 ]) # 2차원 꼴 남기고 5 값 가져오기
print(nums[1, 1:2]) # 1차원 꼴 남기고 5 값 가져오기
print(nums[1, 1]) # 그냥 5 값만 가져오기

[[5]]
[5]
5


In [4]:
# NumPy 배열 사용 시의 주의사항 (python list와는 다름!)
# NumPy 배열에 대한 검색 or 슬라이싱 ==> 주소 복사! ==> 기존 배열 변경 시 같이 변경
# NumPy 배열에 대해 copy() ==> 별도의 독립적인 새로운 공간에 저장!

nums = np.array([1, 4, 2, 5, 3])
ref = nums[1:4]
cpy = nums[1:4].copy()
print(ref)
print(cpy)
nums[2] = 10
print(ref) # 참조(포인터)만 할당한 것이므로 값이 따라서 바뀜
print(cpy) # 별도의 공간이므로 값이 따라 바뀌지 않음

[4 2 5]
[4 2 5]
[ 4 10  5]
[4 2 5]


In [6]:
# cf. 슬라이싱 시, 파이썬 리스트와 넘파이 배열의 차이!

py_list1 = [0, 1, 2, 3]
py_list2 = py_list1[0:2] # 파이썬 리스트의 슬라이싱
print(py_list2)
py_list1[1] = 10
print(py_list1)
print(py_list2) # 파이썬 리스트의 슬라이싱은 별도의 공간에 저장하는 copy()

[0, 1]
[0, 10, 2, 3]
[0, 1]


## NumPy의 내장 함수를 사용한 배열 생성
* 특정 수로 초기화하기 (zeros, ones, full)
* 단위 행렬 생성 (identity, eye)
* 난수 행렬 생성 (ramdom)
* step 배열 생성 (linspace, arange)

In [8]:
# NumPy 내장 함수를 사용한 배열 생성

print(np.zeros((2, 2))) # (2, 2) shape(꼴)로 모든 값이 0인 배열 생성
print(np.ones((1, 2))) # 모두 1로 채워진 배열 생성
print(np.full((2, 2), 7)) # 모든 값이 특정 value(7)로 채워진 특정 꼴(2, 2)의 배열 생성

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]


In [10]:
# NumPY 내장 함수를 사용한 단위행렬(Identity) 생성 & 이동 (k만큼) 

print(np.identity(3)) # 3x3 짜리 단위행렬
print()
print(np.eye(3)) # 3x3 짜리 단위행렬
print()
print(np.eye(3, k=1)) # identity()와 달리, eye()는 이동도 할 수 있음! (x축 방향으로)
print()
print(np.eye(3, k=-2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]


In [12]:
# NumPy의 내장 함수를 사용한 난수 생성 ==> np.random.random(shape)

print(np.random.random((2, 2))) # 0~1 사이의 난수 배열 생성
print()
print(np.random.normal((2, 2))) # 정규분포를 따르는 난수 배열 생성 (0~1 아님!)
print()
print(np.random.randint(1, 100, (2, 2))) # low부터 high 사이의 정수형 난수 배열 생성

[[0.50101921 0.56458774]
 [0.49305735 0.27178861]]

[1.26726509 1.92246002]

[[65  2]
 [79 93]]


In [13]:
# NumPy의 내장 함수를 사용한 일정 간격(step)의 수 배열 생성 (1) ==> np.linspace()

print(np.linspace(0, 1, num = 5, endpoint = True)) 
print(np.linspace(0, 1, num = 5, endpoint = False))
print(np.linspace(0, 1, num = 5, endpoint = False, retstep = True))

# np.linspace(start, end, num, endpoint, retstep) ==> retstep : step 크기 return할지?

[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8]
(array([0. , 0.2, 0.4, 0.6, 0.8]), 0.2)


In [17]:
# NumPy의 내장 함수를 사용한 일정 간격(step)의 수 배열 생성 (2) ==> np.arange()

print(np.arange(0.4, 1.1, 0.1)) # np.arange(start, end, step, dtype)
print(np.arange(1, 3, 1)) # stop(3)은 포함 x

# 따라서, step 크기가 정해져 있을 때 ==> np.arange()
# 몇 등분으로 나눌지 개수가 정해져 있을 때 ==> np.linspace()

[0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[1 2]


## 행열 전환과 형태 변형
* np.reshape()
* T (전치)
* swapaxes()
* transpose()

In [18]:
# 행열 전환과 형태 변형 ==> np.reshape()

sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
print(sap)
sap2d = sap.reshape(2, 4) # reshape 전, 후의 전체 아이템 수는 동일해야 함!
print(sap2d)

['MMM' 'ABT' 'ABBV' 'ACN' 'ACE' 'ATVI' 'ADBE' 'ADT']
[['MMM' 'ABT' 'ABBV' 'ACN']
 ['ACE' 'ATVI' 'ADBE' 'ADT']]


In [19]:
# 행열 전환과 형태 변형 ==> T (전치)

print(sap2d.T) # (2, 4)를 (4, 2)로 변형

[['MMM' 'ACE']
 ['ABT' 'ATVI']
 ['ABBV' 'ADBE']
 ['ACN' 'ADT']]


In [20]:
# 위의 전치 T를 일반화한 함수 ==> np.swapaxes(axis_1, axis_2) ==  T (전치)
print(sap2d) # (2, 4)
print(sap2d.T) # (4, 2)
print(sap2d.swapaxes(0, 1)) # 0번 축 : 행 / 1번 축 : 열 ==> 차원 늘어날 때 쓰기!

[['MMM' 'ABT' 'ABBV' 'ACN']
 ['ACE' 'ATVI' 'ADBE' 'ADT']]
[['MMM' 'ACE']
 ['ABT' 'ATVI']
 ['ABBV' 'ADBE']
 ['ACN' 'ADT']]
[['MMM' 'ACE']
 ['ABT' 'ATVI']
 ['ABBV' 'ADBE']
 ['ACN' 'ADT']]


In [22]:
# 3차원 배열에서의 swapaxes 사용 예제 ==> "가장 마지막"에 추가된 축부터 0번 축!

sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
sap3d = sap.reshape(2, 2, 2)
print(sap3d, '\n')
print()
print(sap3d.swapaxes(1, 2)) # 0 : depth / 1 : 행 / 2 : 열 (열보다 행이 더 나중에 추가)
# 따라서 0번 축인 depth 축은 놔두고 각 채널을 이루는 2차원 배열 각각 T 적용됨

[[['MMM' 'ABT']
  ['ABBV' 'ACN']]

 [['ACE' 'ATVI']
  ['ADBE' 'ADT']]] 


[[['MMM' 'ABBV']
  ['ABT' 'ACN']]

 [['ACE' 'ADBE']
  ['ATVI' 'ADT']]]


In [24]:
# transpose() 함수의 활용 ==> T나 swapaxes 보다 일반적인 함수

sap2d = sap.reshape(2, 4)
print(sap2d)
print()
print(sap2d.T)
print()
print(sap2d.swapaxes(0, 1))
print()
print(sap2d.transpose(1, 0)) # 변형 후의 축의 index 순서대로 기재하기 / 열 -> 행
print()
print(sap2d.transpose(0, 1)) # 행 -> 열 순서 (원래의 순서 그대로 유지!)

[['MMM' 'ABT' 'ABBV' 'ACN']
 ['ACE' 'ATVI' 'ADBE' 'ADT']]

[['MMM' 'ACE']
 ['ABT' 'ATVI']
 ['ABBV' 'ADBE']
 ['ACN' 'ADT']]

[['MMM' 'ACE']
 ['ABT' 'ATVI']
 ['ABBV' 'ADBE']
 ['ACN' 'ADT']]

[['MMM' 'ACE']
 ['ABT' 'ATVI']
 ['ABBV' 'ADBE']
 ['ACN' 'ADT']]

[['MMM' 'ABT' 'ABBV' 'ACN']
 ['ACE' 'ATVI' 'ADBE' 'ADT']]


## NumPy 배열의 연결
* concatenate()
* vstack()
* hstack()

In [26]:
# 여러 1차원 NumPy 배열의 연결 ==> concatenate()

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([4, 5, 6])

print(np.concatenate([x, y, z])) # 2개 이상의 배열을 하나의 array로 연결해줌!

[1 2 3 3 2 1 4 5 6]


In [29]:
# 여러 2차원 배열의 연결 ==> ***가장 마지막에 추가된 축 (0번 축) 방향으로 연결됨!***

grid = np.array([[1, 2, 3], [4, 5, 6]])
print(np.concatenate([grid, grid])) # 0번 축인 행 방향으로 아래로 붙음

print()

# 두번째 인자로 axis = 1 ==> 붙이고 싶은 축 index 지정 가능

print(np.concatenate([grid, grid], axis=1)) # 1번 축 : 열

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [35]:
# 수직 방향으로 병합 ==> vstack()

x = np.array([9, 8, 7])
grid = np.array([[1, 2, 3], [4, 5, 6]])

print(np.vstack([x, grid])) # 이때는 np.concatenate 쓸 수 X ==> x는 1차원, grid는 2차원이므로

print()

print(np.vstack([grid, grid]))
print(np.concatenate([grid, grid])) # 0번축인 행 축으로 == 즉, 수직 방향으로 붙음

[[9 8 7]
 [1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [36]:
# 수평 방향으로 병합 ==> hstack()

y = np.array([[9], [8]])
grid = np.array([[1,2,3], [4, 5, 6]])

print(np.hstack([y, grid])) 

[[9 1 2 3]
 [8 4 5 6]]


## NumPy 배열의 분할
* split()

In [37]:
# split(배열명, 분할 지점의 리스트) ==> 슬라이싱 지점 인덱스들을 리스트로 넣어 주기

x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) # x를 index 3 이전까지 자르고, index 5 이전까지 자르기
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [38]:
# cf. range와 np.arange의 차이

print(range(16))
print(np.arange(16))

range(0, 16)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [46]:
# 2차원 배열의 초기화 및 분할 ==> np.arange() & reshape() / np.split()

grid = np.arange(16).reshape(4, 4) # reshape((4, 4)) 해도 동일!
print(grid)

print()

# 마지막으로 추가된 0번 축이 행이기 때문에, 행을 기준으로 2번 index 이전까지 split!

upper, lower = np.split(grid, [2]) # np.split(배열명, 분할 지점의 리스트)
print(upper)
print()
print(lower)

print()

# 다른 축 방향으로 분할하고자 할 경우 ==> 마지막에 axis 인자 지정해주기!

upper, lower = np.split(grid, [2], axis = 1) # 1번 축 : 열
print(upper)
print()
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
