##  immutable 객체 vs mutable 객체
* **immutable** 객체 : **int, string, tuple**
> += 와 + 간의 차이 X  
* **mutable** 객체 : **np.array, list, dictionary**
> += 와 + 간의 차이 ㅇ (**id 다름**)  
> ***원본은 그대로 둔 상태에서 새롭게 기존 객체가 가리키는 곳이 업데이트 된다!***

### immutable ex)

In [2]:
img = 10
print(img, id(img))

img += 20
print(img, id(img))

10 140729538417760
30 140729538418400


In [3]:
img = 10
print(img, id(img))

img = img + 20
print(img, id(img))

10 140729538417760
30 140729538418400


### mutable ex)

In [4]:
import numpy as np

img_list = np.array([1, 2, 3])
print(img_list, id(img_list))

img_list += 20
print(img_list, id(img_list))

[1 2 3] 1552096927216
[21 22 23] 1552096927216


In [5]:
img_list = np.array([1, 2, 3])
print(img_list, id(img_list))

img_list = img_list + 20
print(img_list, id(img_list))

[1 2 3] 1552100857456
[21 22 23] 1552100857296


<hr>

In [1]:
import cv2 as cv

In [2]:
# 특정 키를 눌렀을 때만 창을 닫게끔
while(True):
    if (cv.waitKey() == 27) : # esc : 27
        break

KeyboardInterrupt: 

In [3]:
# (실습) 마우스 이벤트 처리
import cv2

def on_mouse(event, x, y, flags, param):
    global oldx, oldy
    
    if event == cv2.EVENT_LBUTTONDOWN:
        oldx, oldy = x, y
        print('EVENT_LBUTTONDOWN: %d, %d' % (x, y))
    
    elif event == cv2.EVENT_LBUTTONUP:
        print('EVENT_LBUTTONUP: %d, %d' % (x, y))
    
    elif event == cv2.EVENT_MOUSEMOVE:
        if flags & cv2.EVENT_FLAG_LBUTTON:
            cv2.line(img, (oldx, oldy), (x, y), (0, 255, 255), 2)
            cv2.imshow('img', img) # 아래 함수 밖에서 선언한 img
            oldx, oldy = x, y
            
            
img = cv2.imread('images/lenna.bmp') 

if img is None:
    print('Image load failed!')
    exit() # 프로그램 전체 종료!
    
cv2.namedWindow('img')
cv2.setMouseCallback('img', on_mouse)

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

EVENT_LBUTTONDOWN: 83, 165
EVENT_LBUTTONUP: 391, 438


In [4]:
# (실습) 트랙바 사용하기
import numpy as np
import cv2

def saturated(value):
    # 0보다 작아지거나 255를 넘어버리면 다른 픽셀 값으로 보이므로 예외처리!
    if value > 255:
        value = 255
    elif value < 0: 
        value = 0
        
    return value

def on_level_change(pos): # position
    img[:] = saturated(pos * 16)
    cv2.imshow('image', img)
    
img = np.zeros((400, 400), np.uint8)

cv2.namedWindow('image')
cv2.createTrackbar('level', 'image', 0, 16, on_level_change)

cv2.imshow('image', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
# (실습) 데이터 파일 저장하기
